### ISSUE TITLE
Chapter IV - Mission 03: Frontend doesn't show the translation of my site

### ISSUE THREAD

**Issue by schmidtsabine** [TYPO3GmbH/mainzific_rim#4] opened 2020-07-25 18:02 UTC
What I did: 
I added the language "japanese" to a single site, translated the content elements and enabled the view for every element of the page. In the page settings I activated the check box "hide page if no translation for current language exists" (and in another try I deactivated it).

The new frontend view now shows a language menu with "default" and "japanese" option. 

What I expected: 
Clicking on "japanese" would show the japanese translations of my content elements. 

What happened: 
When I click on "japanese" the URL changes to a different L-number, but the content elements stay in "default" language. In the language menu the "default" ist still the highlighted one. 

For some reason my configuration does not know that I'm trying to access the translated content through clicking on a different language.

**Comment by Weissheiten** [comment] 2020-08-06 09:27
We'll look into that - as first hint, did you follow the Note in the readme?

"Since TYPO3 v9, you will need to provide a site configuration for human readable URLs and beautiful language
menu out of the box. Since the core is not yet ready to get a site configuration injected with a site package, please
find an example configuration, that works nicely with this package, in ext:mainzific_rim/Configuration/sites."
No Error Handling is configured, though.

**Comment by susannemoog** [comment] 2020-08-07 10:17
As @Weissheiten mentioned this is caused by a missing site configuration. I added an additional warning to the README file that a site configuration is necessary for multi-language to work correctly. Closing this issue for now.

**Closed as completed by susannemoog** 2020-08-07 10:17 UTC
